services:
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080" # REST API
      - "5001:8081" # gRPC API
    environment:
      # ASP.NET Core Settings
      - ASPNETCORE_URLS=http://+:8080;http://+:8081
      - ASPNETCORE_ENVIRONMENT=Development

      # Security
      - DataProtection__CertificatePassword=a-secure-password
      - Jwt__Issuer=ck-auth-service
      - Jwt__Audience=ck-gateways

      # Service Connections
      - DatabaseProvider=Postgres
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=authdb;Username=user;Password=password
      - EventBusProvider=Nats
      - Nats__Url=nats://nats:4222
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - dp-keys:/app/.keys
      - ./src/Auth/Api/Certs:/app/Certs:ro

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d authdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.9
    command: ["--http_port", "8222", "-js", "-sd", "/data/jetstream"]
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - nats-data:/data/jetstream

volumes:
  postgres-data:
  dp-keys:
  nats-data:
